# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 174ba6e92c73e7fb06e33aa81eaab628f3fdf83919a1165aa61a03f88df25bd05350412b95aaefbd0d5afbbec3d98ef5d345bae2283b98399bf74218913fdb3d

test:
  secret_key_base: c1d08f831339a852acc91623c10e55f22dc657fa077f6f20d23f5caa5497e6fbe2a54bbc73b39567bf931ac68fee02d458e6c8dde9d6880e0301ac583867216d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
